### PR TITLE
first round of tests for bytescale

### PR DESCRIPTION
**Pull request by joemcglinchy**
added first round of tests for bytescale. still need a test for the case where cmin=cmax, but that's an odd one at first glance.

### CODE REVIEW

**Comment by lwasser** [comment]
hey there @joemcglinchy can you kindly update your fork / branch? there is a conflict here and i think  it's involved with some other tests for other functions that were already on master that are not reflected in your PR. let me know if that is clear as mud :)

**Comment by joemcglinchy** [comment]
not totally clear... update it with what exactly? a `git pull` from an `upstream` branch?

**Comment by lwasser** [comment]
yes you need to update your fork and branch from earthpy/master. YOu can do a reverse pull request to update which is very straight forward! but there are conflicts because you need to update things! drop by if you want me to show you!! git pull from upstream should also work BUT it might be weird as you might need to rebase too?? a reverse pull request should do the trick. i can create one to show you... one min.

**Comment by lwasser** [comment]
https://github.com/joemcglinchy/earthpy/pull/1

see the above PR to see how many commits behind you are!!

**Comment by joemcglinchy** [comment]
makes sense since the `bytescale_tests` was a branch of the `master` branch from my fork, which hadn't been updated!

**Comment by lwasser** [comment]
oops @joemcglinchy you merged this into master.

**Comment by joemcglinchy** [comment]
huh. that's weird! thought I merged it into `bytescale_tests`! at least, that's what I thought I saw here: https://github.com/joemcglinchy/earthpy/pull/1#issuecomment-440043239

**Comment by lwasser** [comment]
is it possible that you pushed up to upstream instead of origin? Did you do anything local? If you did i suspect you pushed to upstream rather than your fork origin and that caused the merge to happen. that would make sense. Maybe you could consider removing the upstream remote if that becomes and issue just to avoid it happening. 

I think this because i see your master branch on your fork is still not up to date with earthpy master -- [see here](https://github.com/joemcglinchy/earthpy/pull/2)  

if you merged, pulled things down locally and pushed to upstream rather than your fork it would merge this PR.

**Pull request merged**
