### PR TITLE
Update order of imports in utils.py and delete commented out code in _init_.py

### PR DESCRIPTION
**Pull request by katysill**
https://github.com/earthlab/earthpy/issues/52

### CODE REVIEW

**Comment by jlpalomino** [comment]
@katysill Thank you for your PR. The proposed changes appropriately address the identified issues. One small thing: please update the title of this PR to be a little more specific about what was done to these two files, similar to issue title but shorter (e.g. Update imports in utils.py...).

**Comment by katysill** [comment]
Thanks for the suggestion. I have revised the title of the PR.

**Comment by jlpalomino** [comment]
@katysill Looks good. A final review will be completed by @lwasser before the changes are merged. Thanks.

**Comment by lwasser** [comment]
Thanks @katysill  @jlpalomino  Katy congrats on your first submission to earthpy and open source efforts!! nice work.

**Pull request merged**
