### PR TITLE
Tif gen 2

### PR DESCRIPTION
**Pull request by joemcglinchy**
this has the most recent commits so generating dummy tif files should not have conflict.

### CODE REVIEW

**Comment by lwasser** [comment]
ok a few things going on here now @joemcglinchy  but this is looking gooood!

the first is please `import os` in the file that contains the `test_dummy_to_writer()` fun . [see here](https://travis-ci.org/earthlab/earthpy/builds/464715673#L1400)

let's fix that first before troubleshooting the epsg issue.. i have some thoughts on it but let's get the tests running first :)

**Comment by joemcglinchy** [comment]
Doh! on the lack of os import. That seems to have fixed the EPSG issue (??), not sure how those are related but this looks good now.

**Comment by joemcglinchy** [comment]
done!

**Comment by lwasser** [comment]
Do you mind also updating the test name to match the fun name? @joemcglinchy thank you so much!! my apologies that this has taken so long to merge. it was one of the first pr's i think. i think we can get it  merged today.

**Comment by lwasser** [comment]
awesome. Thank you @joemcglinchy !! this looks great. merging now!!

**Pull request merged**
