### PR TITLE
Added string documentation to clip_points and clip_line_poly

### PR DESCRIPTION
**Pull request by mcshanec**
https://github.com/earthlab/earthpy/issues/49 

String documentation added for clip_points and clip_line_poly. Both functions in PEP8 format. Commented out code deleted from function body.

### CODE REVIEW

**Comment by jlpalomino** [comment]
@mcshanec This is a good start. A few changes:

1. Please update the title of this PR to "Add docstrings to..." to be more clear.
2. Please modify your docstring in each function in the following ways:

- add subsections for Parameters and Returns (a good example: https://github.com/mapbox/rasterio/blob/master/rasterio/mask.py)
- shorten all of the lines in the docstring, as they are quite long (the mask example from rasterio is good example of that too) 
- modify indentations to match the rasterio example as well 
- there are a few misspellings in the docstrings for clip_points (geomerty) and clip_line_poly (reference areaself)
- remove the single quotes around the word shp in the docstring for clip_line_poly

**Comment by jlpalomino** [comment]
@mcshanec One more small change requested: per PEP 8, please update the docstrings to use double quote `"""`, rather than single quotes `'''`, and start the text on that line like the rasterio example. Thanks.

**Comment by jlpalomino** [comment]
@mcshanec Getting closer!  A few more small changes before the final review by Leah. 

1. Upon closer review of these functions, I realized that the inputs (shp, clip_obj) and the outputs (subset) of both functions are actually geopandas dataframes.  While the original data can come from a shapefile imported into a geopandas dataframe using read_file(), the actual inputs to the functions are geopandas dataframes, as are the output subsets.  Please modify the documentation to replace all mention of shapefiles to geopandas dataframes. 
2. Remove the space between `""" A function to...` in clip_points.
2. Update the following text in clip_points to match your text for clip_line_poly:
`The clip_obj's geometry is dissolved into a
        single geometric feature and intersected with the points
        in the shp input.`
4. Replace this line: 
`Points will be extracted that intersect with the clipping object.`
With your other text that was removed from the clip_obj description:
`Points that intersect with the geometry of clip_obj are
        extracted and returned.`
5. Modify PARAMETERS to separate the parameter name and object type from the description:
`shp: geopandas dataframe`
 `              Point geometry that is to be clipped to clip_obj`  (**note:** this new line should be indented once, but this comment box won't let show that)
6. Same with RETURNS:
`shp: geopandas dataframe`
`The subset of shp that intersects with clip_obj` (**again:** this new line should be indented once, but this comment box won't let show that)

**Comment by jlpalomino** [comment]
@mcshanec Even better! With the new text, a few new things have come up. This is an iterative process but it is almost there!
1. In both functions, please replace all instances of geopanda with geopanda**s**, as this is the correct name.
2. In clip_points, please capitalize the first word in the descriptions after PARAMETERS (lines 21 and 24), like you did for clip_line_poly.
3. clip_points differs from clip_line_poly in that there is no spatial index created for the points. Please revise lines 25-26 to match my previously suggested text: `The clip_obj's geometry is dissolved into a single geometric feature and intersected with the points in the shp input.`. 
4. Remove `attribute table` from line 54 to read: `Data within this intersection is extracted from the shp and`.
5. Remove `down` from line 61 to read: `clipped to the reference`
5. Please use present tense throughout the documentation. Example: rather than `The returned geopandas dataframe will be`, use `The returned geopandas dataframe is the subset of shp`.

**Comment by jlpalomino** [comment]
@mcshanec Apologies for this but I just noticed that the norm seems to be Parameters rather than PARAMETERS and Returns rather than RETURNS. Please update in both functions.

**Comment by jlpalomino** [comment]
@mcshanec Great work. I know iterations can be frustrating. Last changes before I pass it on to Leah. 
1. I see the update to Parameters and Returns was made for clip_line_poly but not for clip_points. 
2. Please remove the extra lines before the final  `"""` at the end of the documentation for clip_line_poly.

**Comment by lwasser** [comment]
ok will hold off on reviewing this until i hear from both @mcshanec and @jlpalomino  @mcshanec you should be responding to Jenny on these comments and tagging her when you are ready for another review. please do that for the next round of edits.

**Comment by mcshanec** [comment]
@jlpalomino I apologize I didn't realize I needed to be commenting back every time you had a correction. I completed all your requests yesterday - is there anything else that I  missed?

**Comment by lwasser** [comment]
Thank you so much @mcshanec !! this looks excellent. Congratulations. As soon as I merge this you will be a new contributor to earthpy! Thank you for your contributions!

**Comment by jlpalomino** [comment]
@mcshanec Looks good. A final review will be completed by @lwasser before the changes are merged. Thanks.

**Comment by jlpalomino** [comment]
@mcshanec @lwasser The perils of real time work. Within two minutes, I hadn't refreshed the page! But glad that your hard work paid off.

**Pull request merged**
