### PR TITLE
Add bumpversion and automate PyPI deployment

### PR DESCRIPTION
**Pull request by mbjoseph**
This PR adds bumpversion as a way to increment versions programmatically, and also adds a skeleton to the Travis build that will automatically deploy new versions of earthpy to PyPI. See the changes in CONTRIBUTING.rst for instructions on how to deploy.

One thing that still needs to be added to this branch @lwasser is your encrypted PyPI password on this line: https://github.com/earthlab/earthpy/compare/add-bumpversion?expand=1#diff-354f30a63fb0907d4ad57269548329e3R43

Instructions for encrypting your password can be found here: https://docs.travis-ci.com/user/deployment/pypi/

@lwasser it would be good if you added your encrypted password to this branch before merging. Note that if your PyPI password contains special characters you need to escape them before encrypting your password.

### CODE REVIEW

**Comment by mbjoseph** [comment]
Closes #180

**Comment by lwasser** [comment]
got it @mbjoseph thank you!! i'll work on this in the next day or two!! much appreciated

**Comment by lwasser** [comment]
ok @mbjoseph  i just added my encypted password. Please let me know if this looks correct. i'm not sure how to test it.

**Comment by mbjoseph** [comment]
Ok this puppy looks ready to merge - we should test with releasing a patch IRL to ensure that it works.

**Pull request merged**
